version: '3'

services:
  MessagingAppDb:
    image: mysql:8.1.0
    ports: 
      - "3306:3306"
    volumes:
      - "MessagingAppDb:/var/lib/mysql"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password1 # Dont use outside of local testing
      
volumes:
  MessagingAppDb: